steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/quick-job-japan-dev/gcp-deploy:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/quick-job-japan-dev/gcp-deploy:$SHORT_SHA']
